name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["Continuous integration of application"]
    types:
      - completed

jobs:
  deploy-api:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check branch is main
        run: |
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          if [ "${{ github.event.workflow_run.head_branch }}" != "main" ]; then
            echo "Not on main branch — skipping deploy"
            exit 1
          fi

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build & Push Docker image (API)
        working-directory: ./api
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/depot-docker/${{ secrets.API_SERVICE_NAME }} .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/depot-docker/${{ secrets.API_SERVICE_NAME }}

      - name: Deploy API to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.API_SERVICE_NAME }} \
            --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/depot-docker/${{ secrets.API_SERVICE_NAME }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --port 3000 \
            --allow-unauthenticated \
            --set-env-vars "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" \
            --set-env-vars "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            --set-env-vars "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" \
            --set-env-vars "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" \
            --set-env-vars "CLIENT_URL=${{ secrets.CLIENT_URL }}" \
            --set-env-vars "JWT_SECRET=${{ secrets.JWT_SECRET }}" \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }}"

  deploy-client:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check branch is main
        run: |
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          if [ "${{ github.event.workflow_run.head_branch }}" != "main" ]; then
            echo "Not on main branch — skipping deploy"
            exit 1
          fi

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build & Push Docker image (Client)
        working-directory: ./client
        run: |
          docker build \
          --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
          -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/depot-docker/${{ secrets.CLIENT_SERVICE_NAME }} .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/depot-docker/${{ secrets.CLIENT_SERVICE_NAME }}

      - name: Deploy Client to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLIENT_SERVICE_NAME }} \
            --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/depot-docker/${{ secrets.CLIENT_SERVICE_NAME }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 80