name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build & Push Docker image (API)
        working-directory: ./api
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/depot-docker/${{ secrets.API_SERVICE_NAME }} .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/depot-docker/${{ secrets.API_SERVICE_NAME }}

      - name: Deploy API to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.API_SERVICE_NAME }} \
            --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/depot-docker/${{ secrets.API_SERVICE_NAME }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated

  deploy-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build & Push Docker image (Client)
        working-directory: ./client
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/depot-docker/${{ secrets.CLIENT_SERVICE_NAME }} .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/depot-docker/${{ secrets.CLIENT_SERVICE_NAME }}

      - name: Deploy Client to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLIENT_SERVICE_NAME }} \
            --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/depot-docker/${{ secrets.CLIENT_SERVICE_NAME }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated